// Desc: Configuration actions for the profile configuration page
export const PROFILE_ACTIONS = [
	{code: 'default', name: 'Profile Overview', description: 'Profile configuration details'},
	{code: 'apps', name: 'Assigned Apps', description: 'Apps visible in the app menu'},
	{code: 'connectedapps', name: 'Assigned Connected Apps', description: 'Connected apps visible in the app menu'},
	{code: 'objects', name: 'Object Settings', description: 'Permissions to access objects and fields'},
	{code: 'apppermissions', name: 'App Permissions', description: 'App-specific action permissions'},
	{code: 'apexaccess', name: 'Apex Class Access', description: 'Permissions to execute Apex classes'},
	{code: 'visualforceaccess', name: 'Visualforce Page Access', description: 'Permissions to execute Visualforce pages'},
	{code: 'externaldatasource', name: 'External Data Source Access', description: 'Authenticate against external data sources'},
	{code: 'namedcredential', name: 'Named Credential Access', description: 'Authenticate against named credentials'},
	{code: 'externalcredential', name: 'External Credential Principal Access', description: 'Authenticate with external credential principal mappings'},
	{code: 'flowaccess', name: 'Flow Access', description: 'Permissions to execute Flows'},
	{code: 'custompermissions', name: 'Custom Permissions', description: 'Access to custom processes and apps'},
	{code: 'custommetadata', name: 'Custom Metadata Types', description: 'Permissions to access custom metadata types'},
	{code: 'customsettings', name: 'Custom Setting Definitions', description: 'Permissions to access custom settings'},
];

export const OBJECT_ACTIONS = {
	standard: [
		{code: 'Details', name: 'Details', description: 'Object Details'},
		{code: 'FieldsAndRelationships', name: 'Fields', description: 'Fields & Relationships'},
		{code: 'RecordTypes', name: 'Record Types', description: 'Object Record Types'},
		{code: 'PageLayouts', name: 'Page Layouts', description: 'Object Page Layouts'},
		{code: 'LightningPages', name: 'Lightning Record Pages', description: 'Lightning Record Pages'},
		{code: 'ButtonsLinksActions', name: 'Buttons, Links, and Actions', description: 'Buttons, Links, and Actions'},
		{code: 'CompactLayouts', name: 'Compact Layouts', description: 'Compact Layouts'},
		{code: 'FieldSets', name: 'Field Sets', description: 'Field Sets'},
		{code: 'ApexTriggers', name: 'Triggers', description: 'Triggers'},
		{code: 'FlowTriggers', name: 'Flow Triggers', description: 'Flow Triggers'},
		{code: 'ObjectAccess', name: 'Object Permissions', description: 'Object Permissions'},
		{code: 'Limits', name: 'Object Limits', description: 'Object Limits'},
		{code: 'ValidationRules', name: 'Validation Rules', description: 'Validation Rules'},
		{code: 'MySearchLayouts', name: 'Search Layouts', description: 'Search Layouts'},
		{code: 'RelatedLookupFilters', name: 'Related Lookup Filters', description: 'Related Lookup Filters'},
		{code: 'AlohaSearchLayouts', name: 'List View Buttons', description: 'List View Button Layout'},
		{code: 'HierarchyColumns', name: 'Hierarchy Columns', description: 'Hierarchy Columns'},
		{code: 'ConditionalFieldFormatting', name: 'Conditional Field Formatting', description: 'Conditional Field Formatting'},
	],
	custom: [
		// {code: 'd', name: 'Details', description: 'Custom Object Details'},
		// {code: 'f', name: 'Fields', description: 'Custom Fields'},
		// {code: 'pl', name: 'Page Layouts', description: 'Custom Page Layouts'},
		// {code: 'rt', name: 'Record Types', description: 'Record Types'},
	],
};
