export const PROFILE_ACTIONS = [
	{code: '', name: 'Profile Overview', description: 'Profile configuration details'},
	{code: 'AssignedApps', name: 'Assigned Apps', description: 'Apps visible in the app menu'},
	{code: 'ConnectedApps', name: 'Assigned Connected Apps', description: 'Connected apps visible in the app menu'},
	{code: 'ObjectsAndTabs', name: 'Object Settings', description: 'Permissions to access objects and fields'},
	{code: 'AppPermissions', name: 'App Permissions', description: 'App-specific action permissions'},
	{code: 'ClassAccess', name: 'Apex Class Access', description: 'Permissions to execute Apex classes'},
	{code: 'PageAccess', name: 'Visualforce Page Access', description: 'Permissions to execute Visualforce pages'},
	{code: 'ExternalDataSourceAccess', name: 'External Data Source Access', description: 'Authenticate against external data sources'},
	{code: 'NamedCredentialAccess', name: 'Named Credential Access', description: 'Authenticate against named credentials'},
	{
		code: 'ExternalCredentialAccess',
		name: 'External Credential Principal Access',
		description: 'Authenticate with external credential principal mappings',
	},
	{code: 'FlowAccess', name: 'Flow Access', description: 'Permissions to execute Flows'},
	{code: 'CustomPermissions', name: 'Custom Permissions', description: 'Access to custom processes and apps'},
	{code: 'CustomMetadataTypes', name: 'Custom Metadata Types', description: 'Permissions to access custom metadata types'},
	{code: 'CustomSettings', name: 'Custom Setting Definitions', description: 'Permissions to access custom settings'},
	{
		code: 'SystemPermissions',
		name: 'System Permissions',
		description: 'Permissions to perform actions that apply across apps, such as "Modify All Data"',
	},
	{code: 'LoginHours', name: 'Login Hours', description: 'Settings that control when users can log in'},
	{code: 'LoginIPRanges', name: 'Login IP Ranges', description: 'Settings that control the IP addresses from which users can log in'},
	{code: 'ServiceProviders', name: 'Service Providers', description: 'Permissions that let users switch to other websites using single sign-on'},
	{
		code: 'SessionSettings',
		name: 'Session Settings',
		description: 'Settings that control required session security level and timeout for inactive sessions',
	},
	{code: 'PasswordPolicies', name: 'Password Policies', description: 'Profile Based password policies'},
	{code: 'NetworkAffinity', name: 'Default Experience', description: 'Setting for assigning a default community to a user profile'},
];

export const OBJECT_ACTIONS = {
	standard: [
		{code: 'TAB', name: 'Records Tab', description: 'Navigate to Records Tab or List View'},
		{code: 'Details', name: 'Details', description: 'Object Details'},
		{code: 'FieldsAndRelationships', name: 'Fields', description: 'Fields & Relationships'},
		{code: 'RecordTypes', name: 'Record Types', description: 'Object Record Types'},
		{code: 'PageLayouts', name: 'Page Layouts', description: 'Object Page Layouts'},
		{code: 'LightningPages', name: 'Lightning Record Pages', description: 'Lightning Record Pages'},
		{code: 'ButtonsLinksActions', name: 'Buttons, Links, and Actions', description: 'Buttons, Links, and Actions'},
		{code: 'CompactLayouts', name: 'Compact Layouts', description: 'Compact Layouts'},
		{code: 'FieldSets', name: 'Field Sets', description: 'Field Sets'},
		{code: 'ApexTriggers', name: 'Triggers', description: 'Triggers'},
		{code: 'FlowTriggers', name: 'Flow Triggers', description: 'Flow Triggers'},
		{code: 'ObjectAccess', name: 'Object Permissions', description: 'Object Permissions'},
		{code: 'Limits', name: 'Object Limits', description: 'Object Limits'},
		{code: 'ValidationRules', name: 'Validation Rules', description: 'Validation Rules'},
		{code: 'MySearchLayouts', name: 'Search Layouts', description: 'Search Layouts'},
		{code: 'RelatedLookupFilters', name: 'Related Lookup Filters', description: 'Related Lookup Filters'},
		{code: 'AlohaSearchLayouts', name: 'List View Buttons', description: 'List View Button Layout'},
		{code: 'HierarchyColumns', name: 'Hierarchy Columns', description: 'Hierarchy Columns'},
		{code: 'ConditionalFieldFormatting', name: 'Conditional Field Formatting', description: 'Conditional Field Formatting'},
	],
	custom: [
		// {code: 'd', name: 'Details', description: 'Custom Object Details'},
		// {code: 'f', name: 'Fields', description: 'Custom Fields'},
		// {code: 'pl', name: 'Page Layouts', description: 'Custom Page Layouts'},
		// {code: 'rt', name: 'Record Types', description: 'Record Types'},
	],
};
